### ISSUE TITLE
Compose completions should consider the prefix when suggesting items

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#118]
We should be suggesting `command` here.
```YAML
services:
  backend:
    image: alpine
    comm
```
![Image](https://github.com/user-attachments/assets/f00a2925-ec57-48a4-b20c-e91acde88c41)
