### ISSUE TITLE
Suggest dependent services when invoking code completion in `depends_on`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#131]
Given this YAML file, we should suggest `test2` as it is another service that could be a dependency for `test`. We should support this for both as an array item or as an object.
```YAML
services:
  test:
    image: alpine
    depends_on:
      - 
  test2:
    image: alpine
```
```YAML
services:
  test:
    image: alpine
    depends_on:
      
  test2:
    image: alpine
```
