### ISSUE TITLE
Suggest network names when invoking code completion in `networks`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#132]
Given this YAML file, we should suggest `abc` as it is a network could be set as a network for the `test` service. We should support this for both as an array item or as an object.
```YAML
services:
  test:
    image: alpine
    networks:
      - 
networks:
  abc:
```
```YAML
services:
  test:
    image: alpine
    networks:
      
networks:
  abc:
```
