### ISSUE TITLE
Suggest volume names when invoking code completion in `volumes`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#133]
Given this YAML file, we should suggest `abc` as it is a volume could be set as a network for the `test` service. We should support this for both as an array item or as an object. We should _not_ simply insert `abc` though as it expects a mount path `abc:/mount/path/here`
```YAML
services:
  test:
    image: alpine
    volumes:
      - 
volumes:
  abc:
```
```YAML
services:
  test:
    image: alpine
    volumes:
      
volumes:
  abc:
```
