### ISSUE TITLE
Suggest dependent configs when invoking code completion in `configs`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#134]
We should suggest `my_config` when using an array of strings for the `configs` attribute under the top level `services` element.
```YAML
services:
  test:
    image: alpine
    configs:
      - 
configs:
  my_config:
    file: ./my_config.txt
```
