### ISSUE TITLE
Suggest dependent secrets when invoking code completion in `secrets`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#135]
We should suggest `server-certificate` when using an array of strings for the `secrets` attribute under the top level `services` element.
```YAML
services:
  frontend:
    image: alpine:3.21
    secrets:
      - 
secrets:
  server-certificate:
    file: ./server.cert
```
