### ISSUE TITLE
Support `textDocument/definition` requests for volumes

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#147]
We need to support looking up a volume without a mount path, with a mount path, and as an object with the `source` attribute.
```YAML
services:
  test:
    volumes:
      - test2
volumes:
  test2:
```
```YAML
services:
  test:
    volumes:
      - test2:/mount/path
volumes:
  test2:
```
```YAML
services:
  test:
    volumes:
      - source: test2
volumes:
  test2:
```
