### ISSUE TITLE
Show redefined attribute's original value as an inlay hint when extending services in Compose

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#156]
Given this YAML file, we should use an inlay hint to show the original value of `hostname` from `test` since `test2` has chosen to override this value. We will only consider service extensions in the current file for starters.
```YAML
services:
  test:
    image: redis:alpine
    hostname: hello
  test2:
    extends: test
    hostname: world
```
