### ISSUE TITLE
Show extended service's information as a hover

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#157]
```YAML
services:
  test:
    image: redis:alpine
    hostname: hello
  test2:
    extends: test
```
When hovering over `test2`, it would be useful to know that `image` and `hostname` is being inherited. We will need to see what kind of information we get from performing a resolution with the Compose APIs. From there, we can make a decision as to what path we want to go down:
- use the resolution information from the Compose APIs directly
- use the resolution information from the Compose APIs but then perform some kind of filtering on it
- just reuse the YAML text as-is without using any Compose APIs
