### ISSUE TITLE
No completion items suggested for an array schema that does not use `oneOf`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#161]
```YAML
services:
  postgres:
    develop:
      watch:
        - 
```
We are not suggesting any items for the array of items under `watch`.
