### ISSUE TITLE
Consider `extends` for searching for named service references

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#170]
We should include `extends` when searching for named service references. 
```YAML
services:
  test:
    image: alpine
  test3:
    image: alpine
    extends: test
    depends_on: 
    - test
```
