### ISSUE TITLE
Allow opening the `extends.file` attribute of a service

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#172]
```YAML
services:
  test2:
    extends:
      service: test
      file: ./compose.other.yaml
```
We should allow opening `compose.other.yaml` as a link. We will need to augment the `textDocument/documentLink` request for this. This should be achievable by modifying the code below to consider an `extends` object and then by reusing the `types.AbsolutePath` function. We can also reference what was done in `createIncludeLink` to create the appropriate link result.

https://github.com/docker/docker-language-server/blob/351618a33dba1ef9f94a67461531004b13d27202/internal/compose/documentLink.go#L110-L122
