### ISSUE TITLE
Suggest build targets from the Dockerfile

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#173]
```YAML
services:
  test:
    build:
      target: 
```
When invoking code completion for the `build.target` attribute, we should suggest build stages.
