### ISSUE TITLE
Suggest service names as completion items for `extends`

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#184]
We should suggest service names for `extends` and `extends.service`.
```YAML
services:
  test:
    image: alpine
    extends: 
  test2:
    image: alpine
```
```YAML
services:
  test:
    image: alpine
    extends:
      service: 
  test2:
    image: alpine
```
