### ISSUE TITLE
Support using `textDocument/definition` to open dependencies from another file

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#190]
Given these YAML files, we should be able to use `textDocument/definition` to open `otherService` from the `test` service and have it jump to and open `compose.other.yaml`.
```YAML
include:
  - compose.other.yaml

services:
  test:
    extends: otherService
```
```YAML
services:
  otherService:
    image: alpine:3.21
```
