### ISSUE TITLE
Support hovering over service references that exist in another file

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#207]
```YAML
include:
  - compose.other.yaml

services:
  test:
    extends: otherService
```
```YAML
services:
  otherService:
    image: alpine:3.21
```
Building on the work for #157, we should allow hovering over `otherService` in the first file and seeing YAML content from the second file resolved.
