### ISSUE TITLE
Add custom code completion options for custom Compose provider services

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#212]
Docker Compose 2.36.0 added support for [provider services](https://docs.docker.com/compose/how-tos/provider-services/). To make this feature a little easier to use, we will add custom completion items for `provider` and its child attributes.
```YAML
services:
  ai-runner:
    provider:
      type: model
      options:
        model: ai/example-model
```
We'll use snippets to auto-suggest `type: ${1:model}` and if it's a model we can add suggestions for `model: ${1:ai/example-model}` as well to make it easy for users to use the Docker Model Runner with Docker Compose.
