### ISSUE TITLE
Hover result missing for the `develop` attribute

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#233]
https://github.com/docker/docker-language-server/blob/e0daacee43c6a6605a9dd9784fb6c1423940b379/internal/compose/compose-spec.json#L924-L926

```YAML
services:
  testService:
    develop:
```

Hovering over `develop` does not give us any result but it _does_ have a description in the schema.
