### ISSUE TITLE
Quoted image value can cause the link to be correct

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#242]
<img width="181" alt="Image" src="https://github.com/user-attachments/assets/0b2641e6-b1d0-4bfb-aa13-1a6b6b40b254" />

```YAML
services:
  test:
    image: "alpine"
```

We need to account for the quotes and render the link in the right spot.
