### ISSUE TITLE
Reference range calculation is wrong if the string is quoted

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#255]
<img width="292" alt="Image" src="https://github.com/user-attachments/assets/ebb8787a-5c0f-43b1-8cfd-20e189df0e60" />

The highlighting range is incorrect so this issue affects `textDocument/rename` _and_ `textDocument/prepareRename` as well.

```YAML
services:
  backend:
    image: example/backend
    volumes:
      - type: volume
        source: "db-data"
        target: /data
      - "db-data:/lib/"
      - "db-data:/lib/:ro"
volumes:
  db-data:
    driver: custom
```
