### ISSUE TITLE
Return document link for a config object's `file` attribute

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#271]
We should return a link for the `file` attribute here.
```YAML
configs:
  http_config:
    file: ./httpd.conf
```
