### ISSUE TITLE
Return document link for a secret object's `file` attribute

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#272]
We should return a link for the `file` attribute here.
```YAML
secrets:
  server-certificate:
    file: ./server.cert
```
