### ISSUE TITLE
Disable service suggestion if another file is being referenced

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#285]
Since we are referencing another file for `extends` here, we should not be suggesting `backend` as that is a service in the current file.
```YAML
services:
  frontend:
    image: front
    extends:
      file: non-existent.yaml
      service: 
  backend:
    image: back
```
```JSON
{
    "textDocument": {
        "uri": "file:///tmp/compose.yml"
    },
    "position": {
        "line": 5,
        "character": 15
    },
    "context": {
        "triggerKind": 1
    }
}
```
```JSON
{
    "isIncomplete": false,
    "items": [
        {
            "label": "backend",
            "textEdit": {
                "range": {
                    "start": {
                        "line": 5,
                        "character": 15
                    },
                    "end": {
                        "line": 5,
                        "character": 15
                    }
                },
                "newText": "backend"
            }
        }
    ]
}
```
