### ISSUE TITLE
YAML anchors cause reference lookups to be incorrect

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#287]
The repeated use of `second` can confuse:
- `textDocument/definition`
- `textDocument/documentHighlight`
- `textDocument/prepareRename`
- `textDocument/rename`

This affects `services`, `networks`, `volumes`, `configs`, and `secrets`.
```YAML
services:
  first: &second
    image: redis:8-alpine
    depends_on:
      - second
  second:
    image: redis:7-alpine
```
