### ISSUE TITLE
Resolve YAML anchors when hovering

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#303]
```YAML
services:
  &anchor abc:
    image: alpine:3.21
```
Hovering over `image` will not return anything. We need to resolve the `&anchor` when constructing the node path.
