### ISSUE TITLE
Support resolving anchors when looking up references

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#305]
```YAML
services:
  test:
    image: alpine
  test2:
    extends:
      &anchor service: test
networks:
  test:
```
The `&anchor` on the `service` attribute interrupts the reference processing we have in place for `test`. We need to add support for YAML anchors in our reference processing code and recurse into the actual YAML node the anchor is pointing at where applicable.
