### ISSUE TITLE
Code completion for volume attributes are missing if volumes are defined

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#309]
```YAML
volumes:
  vol:
services:
  test:
    image: alpine
    volumes:
      - 
```
If the `volumes` object is there then using code completion will only suggest `vol`. If `volumes` is deleted then a volume's attribute will show up. The volume attributes should be showing even if we find named references available as suggestions.
