### ISSUE TITLE
Handle anchors when returning document links

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#329]
The `&anchor` is preventing links from being returned from the fourth line. We should get two results instead of one so we need to add support for anchors in our document link handling code.
```YAML
services:
  backend:
    build: &anchor
      dockerfile: Dockerfile
  backend2:
    build:
      dockerfile: Dockerfile
```
```JSON
[
    {
        "range": {
            "start": {
                "line": 6,
                "character": 18
            },
            "end": {
                "line": 6,
                "character": 28
            }
        },
        "target": "file:///Users/rcjsuen/tmp/empty/Dockerfile",
        "tooltip": "/Users/rcjsuen/tmp/empty/Dockerfile"
    }
]
```
