### ISSUE TITLE
Support `textDocument/definition` in Compose files (short syntax form of `depends_on`)

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#67]
We should be able to jump from `db` to the actual service definition.
```YAML
services:
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```
