### ISSUE TITLE
Support `textDocument/definition` in Compose files (long syntax form of `depends_on`)

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#68]
We should be able to jump from `db` or `redis` to the actual service definition. Also see #67.
```YAML
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
  redis:
    image: redis
  db:
    image: postgres
```
