### ISSUE TITLE
Allow jumping to a Dockerfile from a Compose file's `dockerfile` attribute inside the `build` specification

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#69]
We should include a result for jumping to `../backend.Dockerfile` when responding to a `textDocument/documentLink` request.
```YAML
services:
  frontend:
    image: example/webapp
    build: ./webapp

  backend:
    image: example/database
    build:
      context: backend
      dockerfile: ../backend.Dockerfile

  custom:
    build: ~/custom
```
