### ISSUE TITLE
Link the short form syntax of `depends_on` to the defined service for `textDocument/documentHighlight` requests

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#70]
We should highlight the two instances of `db` and `redis` correctly if we receive a `textDocument/documentHighlight` request. We should also return a single element if the cursor is on `web`.
```YAML
services:
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```
