### ISSUE TITLE
Link the long form syntax of `depends_on` to the defined service for `textDocument/documentHighlight` requests

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#71]
We should highlight the two instances of `db` and `redis` correctly if we receive a `textDocument/documentHighlight` request. We should also return a single element if the cursor is on `web`.
```YAML
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
  redis:
    image: redis
  db:
    image: postgres
```
