### ISSUE TITLE
Support `textDocument/definition` requests for referenced config, network, and secret names

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#91]
We should be able to navigate from the name reference to the declared object itself. This follows the work that was implemented for #67.
```YAML
services:
  test:
    image: alpine:3.21
    networks:
    - abc
    configs:
    - def
    secrets:
    - abcd

networks:
  abc:

configs:
  def:
    file: ./httpd.conf

secrets:
  abcd:
    environment: "PATH"
```
