### ISSUE TITLE
Suggest items when using code completion for an array's item

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#95]
```YAML
services:
  test:
    image: alpine:3.21
    configs:
    - 
```
We should suggest the five properties of `service_config_or_secret` when invoking code completion on the fifth line.
https://github.com/docker/docker-language-server/blob/dccfb86565c7a2471fb06f924e030516cb83e7c1/internal/compose/compose-spec.json#L991-L997
