### ISSUE TITLE
Support `textDocument/documentLink` requests to jump to container registries in Compose files

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker-language-server#98]
We should support opening the websites for the following images.
```YAML
services:
  test:
    image: alpine
  test2:
    image: mcr.microsoft.com/powershell
  test3:
    image: ghcr.io/super-linter/super-linter
  test4:
    image: quay.io/prometheus/node-exporter
```
